inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "spec/dummy/**/*"
Style/AndOr:
  EnforcedStyle: conditionals
Style/CaseIndentation:
  IndentOneStep: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/VariableNumber:
  EnforcedStyle: snake_case
Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*"
Metrics/LineLength:
  Max: 100
  Exclude:
    - "lib/navigator/menu.rb"
    - "spec/lib/menu_spec.rb"
Metrics/ParameterLists:
  Max: 3
