language: ruby
rvm:
  - 2.0.0
  - 2.1.0
gemfile:
  - gemfiles/rails-4.0.x.gemfile
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "YE6VB1/VMFreblU5Q6mb+8DKr8BcKY9WkpUOb96FdOYkn7xpYC7FmnE/J0uF\nxqrdAUWJ7I2HRohcqYuAG6SELJDtafCD4R2IIZH3jcBJLtBAdODBMFfv1bjo\nnKqqgzbKTEgL0Mxymw+nWQyYU8SE8claH1ZTKoS4F2KvqKWoaL8="
