# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931b4fee88f27365d5437ba25c876a20db6b1cf18bd590fe6474f484e8db774014c32a0cae7a0b2a7829d7e6208fde995fc3f348baf8add615c389bfd03f9af5

test:
  secret_key_base: 13d5f0da3511ed7f779b02b4affeab167c8073857b7285a13d71c311c62c527c572664d4ebb38280408870958884a3998ad065e0152448e401afedf68638f9b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
