production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dummy_development

stage:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dummy_development

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dummy_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dummy_test
